### PR TITLE
Addresses Issue #27 - Feature Request - Add Auth0 as a provider

### PR DESCRIPTION
**Pull request by saitanay**
Addresses https://github.com/trilbymedia/grav-plugin-login-oauth2/issues/27
Adds Auth0 as a provider for the existing plugin.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for your work on this @saitanay much appreciated!

**Review by w00fz — COMMENTED** [review]
We usually only allow official `league` providers into the main oauth2 plugin and then have the 3rd party as part of [oauth2-extras](https://github.com/trilbymedia/grav-plugin-login-oauth2-extras), or alternatively could be as a separate plugin, like:

* [oauth2-slack](https://github.com/trilbymedia/grav-plugin-login-oauth2-slack)
* [oauth2-discord](https://github.com/trilbymedia/grav-plugin-login-oauth2-discord)
* [oauth2-apple](https://github.com/trilbymedia/grav-plugin-login-oauth2-apple)

Although, with `auth0` being such popular choice and such a universal login, I am wondering if we should include it with the core oauth2 plugin.

Thoughts @rhukster ?

**Comment by RCheesley** [comment]
I thought it was listed, see my comments in the issue? https://github.com/trilbymedia/grav-plugin-login-oauth2/issues/27#issuecomment-563448007

**Comment by RCheesley** [comment]
Oh sorry you mean that you don’t support third party but only those directly included? Do we need to make the PR against the extras repo instead?

**Comment by w00fz** [comment]
Yes. I mean, we do support them in the oauth2-extras, we just haven't included a 3rd party one in the core oauth2 plugin yet.

I am not saying this is not happening, I'm just wandering if auth0 popularity is enough for us to make an exception here 😃

**Comment by saitanay** [comment]
@rhukster @w00fz @RCheesley 

Sounds fair. If you think this should be a separate plugin on its own, here it is - 
https://github.com/saitanay/grav-plugin-login-o-auth2-auth0

Once reviewed, you may add it to the plugin listing as requested on https://github.com/getgrav/grav/issues/2830

**Comment by saitanay** [comment]
The PR is no more required. In favor of
https://github.com/saitanay/grav-plugin-login-oauth2-auth0

Closing

**Pull request closed without merging**
